### ISSUE TITLE
error: panic: helm exited with status 1:

### ISSUE THREAD

**Issue by bcashier** [roboll/helmfile#1044]
I am getting error when I launch this cmmand:
`helmfile apply`

```

panic: helm exited with status 1:
  

goroutine 1 [running]:
github.com/roboll/helmfile/pkg/helmexec.detectHelm3(0x1342b80, 0x4, 0xc00000e308, 0x15e3a00, 0xc00036d260, 0xc000328960)
	/home/circleci/workspace/helmfile/pkg/helmexec/exec.go:59 +0x18e
github.com/roboll/helmfile/pkg/helmexec.New(...)
	/home/circleci/workspace/helmfile/pkg/helmexec/exec.go:68
github.com/roboll/helmfile/pkg/app.New(0x1613620, 0xc000371050, 0x1613620)
	/home/circleci/workspace/helmfile/pkg/app/app.go:73 +0x310
main.action.func1(0xc000105600, 0x0, 0xc000105600)
	/home/circleci/workspace/helmfile/main.go:618 +0xad
github.com/urfave/cli.HandleAction(0x1105560, 0xc000370ba0, 0xc000105600, 0xc0003e8100, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0x1343a48, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x137ec88, 0x3f, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x991
github.com/urfave/cli.(*App).Run(0xc0003841a0, 0xc000030100, 0x4, 0x4, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6ab
main.main()
	/home/circleci/workspace/helmfile/main.go:457 +0x2f32

```

OS: Ubuntu 16.04
helmfile version v0.97.0

**Comment by mumoshu** [comment]
@bcashier Could you paste output of `helm version`, and your helmfile.yaml for repro?

**Comment by mumoshu** [comment]
I'm closing this as unreproducible for now, but please feel free to reopen when you respond!
