### ISSUE TITLE
Runtime error when the `releases[].chart` key is not set

### ISSUE THREAD

**Issue by xadhatter** [roboll/helmfile#1063]
I receive a `panic: runtime error: index out of range [0] with length 0` when the `releases[].chart` key is not set.  Version 0.79.4 and prior of helmfile would default to using the current directory.  As an example:

**helmfile.yaml**
```yaml
releases:
- name: test
  namespace: test
```
**Helmfile v0.79.4**
```
$ helmfile -version
helmfile version v0.79.4

$ helmfile template --skip-deps                 
---
...
```
**Helmfile  v0.98.1**
```
$ helmfile -version
helmfile version v0.98.1

$ helmfile template --skip-deps
panic: runtime error: index out of range [0] with length 0

goroutine 32 [running]:
github.com/roboll/helmfile/pkg/state.normalizeChart(0x1342c94, 0x1, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/workspace/helmfile/pkg/state/util.go:48 +0xf5
github.com/roboll/helmfile/pkg/state.(*HelmState).downloadCharts.func2(0x1)
        /home/circleci/workspace/helmfile/pkg/state/state.go:707 +0x133
github.com/roboll/helmfile/pkg/state.(*HelmState).scatterGather.func1(0xc0004d0000, 0xc00003e190, 0xc0003fc6e0, 0xc00003e1a0, 0x1)
        /home/circleci/workspace/helmfile/pkg/state/state_run.go:42 +0x124
created by github.com/roboll/helmfile/pkg/state.(*HelmState).scatterGather
        /home/circleci/workspace/helmfile/pkg/state/state_run.go:40 +0x1bc
```
If the hemfile.yaml is updated as such, later versions work as expected.

**helmfile.yaml**
```yaml
releases:
- name: test
  namespace: test
  chart: .
```

**Comment by pando85** [comment]
Same here:
```
# helmfile --version
helmfile version v0.125.7
```

```
# helmfile template --skip-deps
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/roboll/helmfile/pkg/helmexec.getHelmVersion(0x15fab93, 0x4, 0xc0007a56d0, 0x1b5f5e0, 0xc0002fc240, 0x0, 0x0, 0x0)
	/home/circleci/workspace/helmfile/pkg/helmexec/exec.go:68 +0x55c
github.com/roboll/helmfile/pkg/helmexec.New(...)
	/home/circleci/workspace/helmfile/pkg/helmexec/exec.go:106
github.com/roboll/helmfile/pkg/app.(*App).getHelm(0xc000400120, 0xc000274000, 0x0, 0x0)
	/home/circleci/workspace/helmfile/pkg/app/app.go:555 +0x281
github.com/roboll/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport.func1(0xc000274000, 0xc000274000, 0x0, 0x0, 0xc0000edb80)
	/home/circleci/workspace/helmfile/pkg/app/app.go:814 +0x41
github.com/roboll/helmfile/pkg/app.(*App).visitStates.func1(0x16056e1, 0xd, 0xc0007bb700, 0x3a, 0x0, 0x0)
	/home/circleci/workspace/helmfile/pkg/app/app.go:654 +0x7ec
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles.func1(0x0, 0x15f9a15)
	/home/circleci/workspace/helmfile/pkg/app/app.go:488 +0x9d
github.com/roboll/helmfile/pkg/app.(*App).within(0xc000400120, 0x15f9a15, 0x1, 0xc00081e470, 0xc00081e430, 0x2)
	/home/circleci/workspace/helmfile/pkg/app/app.go:430 +0x602
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles(0xc000400120, 0x0, 0x0, 0x25e6d30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/workspace/helmfile/pkg/app/app.go:482 +0x2f2
github.com/roboll/helmfile/pkg/app.(*App).visitStates(0xc000400120, 0x0, 0x0, 0x25e6d30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/workspace/helmfile/pkg/app/app.go:566 +0x10b
github.com/roboll/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport(0xc000400120, 0x0, 0x0, 0xc00081e790, 0xc00081e7f8, 0x1, 0x1, 0x1, 0xc0007b1d50)
	/home/circleci/workspace/helmfile/pkg/app/app.go:821 +0x4c1
github.com/roboll/helmfile/pkg/app.(*App).ForEachState(0xc000400120, 0xc00081e800, 0xc00081e7f8, 0x1, 0x1, 0x40a118, 0x15d89e0)
	/home/circleci/workspace/helmfile/pkg/app/app.go:702 +0xb2
github.com/roboll/helmfile/pkg/app.(*App).Template(0xc000400120, 0x1b91d60, 0xc000795d70, 0xc000795d70, 0xc0007a56d0)
	/home/circleci/workspace/helmfile/pkg/app/app.go:218 +0xad
main.main.func5(0xc000400120, 0xc0002069a0, 0x0, 0xc000795d60, 0x0)
	/home/circleci/workspace/helmfile/main.go:257 +0x6d
main.action.func1(0xc0002069a0, 0x0, 0xc0002069a0)
	/home/circleci/workspace/helmfile/main.go:698 +0xd4
github.com/urfave/cli.HandleAction(0x1374140, 0xc0007957f0, 0xc0002069a0, 0xc00079fb00, 0x0)
	/home/circleci/workspace/helmfile/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0x160044b, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x163e767, 0x3d, 0x0, ...)
	/home/circleci/workspace/helmfile/vendor/github.com/urfave/cli/command.go:210 +0x9e8
github.com/urfave/cli.(*App).Run(0xc0004e04e0, 0xc00018c000, 0x2, 0x2, 0x0, 0x0)
	/home/circleci/workspace/helmfile/vendor/github.com/urfave/cli/app.go:255 +0x741
main.main()
	/home/circleci/workspace/helmfile/main.go:500 +0x354d
```
Also fails: diff, apply...

**Comment by mumoshu** [comment]
@pando85 According to the stack trace, yours seems to be #1427, which is being fixed in the next patch release

**Comment by pando85** [comment]
@mumoshu thank you very much.
