### ISSUE TITLE
panic: unexpected error: pipe: too many open files

### ISSUE THREAD

**Issue by mhyousefi** [roboll/helmfile#1066]
I am trying to apply a `helmfile` containing about 60 Node JS and Python micro-services. It used to work smoothly before. Recently, though, I am getting the following error:

```
Building dependency release=release-1, chart=charts/common
Building dependency release=release-2, chart=charts/common
.
.
.
Building dependency release=release-60, chart=charts/common
Comparing release=release-1, chart=charts/common
Comparing release=release-2, chart=charts/common
.
.
.
Comparing release=release-60, chart=charts/common
panic: unexpected error: pipe: too many open files

goroutine 639 [running]:
github.com/roboll/helmfile/pkg/helmexec.combinedOutput(0xc0003102c0, 0xc000010310, 0x54, 0xc0005b5a40, 0xc000396000, 0x54, 0x80)
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/helmexec/runner.go:69 +0x45a
github.com/roboll/helmfile/pkg/helmexec.ShellRunner.Execute(0x0, 0x0, 0xc000010310, 0x1f49ba4, 0x4, 0xc00001ac30, 0xf, 0xf, 0xc0005b5a40, 0x100bb2b, ...)
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/helmexec/runner.go:36 +0xd9
github.com/roboll/helmfile/pkg/helmexec.(*execer).exec(0xc00040e000, 0xc00001ac30, 0xf, 0xf, 0xc0005b5a40, 0x9, 0x10, 0x9, 0x0, 0x0)
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/helmexec/exec.go:329 +0x370
github.com/roboll/helmfile/pkg/helmexec.(*execer).DiffRelease(0xc00040e000, 0x0, 0x0, 0x0, 0xa, 0x27, 0xc00035ef20, 0x15, 0xc00003af50, 0xd, ...)
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/helmexec/exec.go:262 +0x367
github.com/roboll/helmfile/pkg/state.(*HelmState).DiffReleases.func2(0x27)
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/state/state.go:1127 +0x2b6
github.com/roboll/helmfile/pkg/state.(*HelmState).scatterGather.func1(0xc000438900, 0xc00050adf8, 0xc0004e4c00, 0xc00050ae00, 0x27)
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/state/state_run.go:42 +0x124
created by github.com/roboll/helmfile/pkg/state.(*HelmState).scatterGather
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/state/state_run.go:40 +0x1bc
```

Well, I can apply my releases half at a time, but I suppose this should not be the case.
Any help is appreciated.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version` : 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mumoshu** [comment]
@mhyousefi Hey! I wondered if Helmfile has a kind of resource leak that prevents it from successfully running for so many releases, but apparently not.

One of the possible scenarios is that some OS has relatively lower ulimit on number of file descriptors and it results in unable to run 60 concurrent helm processes. Yes, helmfile processes all the releases concurrently by default:

```
$ helmfile apply --help | grep concurrency
   --concurrency value           maximum number of concurrent helm processes to run, 0 is unlimited (default: 0)
```

So, my suggestion is - could you try setting e.g. `--concurrency 30` to `helmfile` commands, so that it looks like `helmfile apply --concurrency 30` to see if it makes difference?

You can then gradually increase it to fine-tune until it finally result in the `too many open files` for maximum concurrency.

**Comment by mhyousefi** [comment]
Thank you for your assistance!

Using the `--concurrency 54` flag, I was able to apply all 60 of my releases. 

Then, I played around with the `ulimit` command. The result of `ulimit -a` was as follows:
```
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       1392
-n: file descriptors                256
```

I did `ulimit -n 257`, increasing the file descriptors limit by one. Doing so, `helmfile -f FILE_PATH apply` was successful.
