### ISSUE TITLE
panic: unexpected error: fork/exec /usr/local/bin/kubectl apply -f namespace.yaml: no such file or directory

### ISSUE THREAD

**Issue by korporationcl** [roboll/helmfile#1274]
Hi, firstly, I just starting evaluating the tool to include it in our pipeline, however, I wanted to test locally what would the tool do in a --dry-run mode, I found a post somewhere that `helmfile --log-level=debug template` would give me a condensed view of the results that helm will apply, but instead I got a **panic** with the following message:

```
panic: unexpected error: fork/exec /usr/local/bin/kubectl apply -f namespace.yaml: no such file or directory

goroutine 1 [running]:
github.com/roboll/helmfile/pkg/helmexec.combinedOutput(0xc00030e9a0, 0x0, 0x25, 0xc00066e4b0, 0xc000088c00, 0x25, 0x40)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/helmexec/runner.go:70 +0x59f
github.com/roboll/helmfile/pkg/helmexec.ShellRunner.Execute(0x2131895, 0x1, 0x0, 0xc0003a6030, 0x2e, 0x30a68d0, 0x0, 0x0, 0xc00066e4b0, 0xc00066e4b0, ...)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/helmexec/runner.go:36 +0xd9
github.com/roboll/helmfile/pkg/event.(*Bus).Trigger(0xc000571008, 0x2136ac0, 0x7, 0x0, 0x0, 0xc000570fd8, 0x400, 0x203000, 0x400)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/event/bus.go:96 +0x906
github.com/roboll/helmfile/pkg/state.(*HelmState).triggerReleaseEvent(0xc0000d0d80, 0x2136ac0, 0x7, 0x0, 0x0, 0xc0005ea000, 0x213806b, 0x8, 0x0, 0x0, ...)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/state/state.go:1452 +0x2d0
github.com/roboll/helmfile/pkg/state.(*HelmState).triggerPrepareEvent(...)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/state/state.go:1423
github.com/roboll/helmfile/pkg/state.(*HelmState).PrepareReleases(0xc0000d0d80, 0x26b3300, 0xc000414180, 0x213806b, 0x8, 0x0, 0x0, 0x203000)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/state/state.go:1403 +0x165
github.com/roboll/helmfile/pkg/app.(*App).template(0xc0002cca20, 0xc0003ac870, 0x26a62a0, 0xc0004bf5e0, 0x30, 0x2038220, 0xc0002ccb01, 0xc0003ac870)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:1159 +0x17a
github.com/roboll/helmfile/pkg/app.(*App).Template.func1(0xc0003ac870, 0xc0003ac870, 0x26b3300, 0xc000414180, 0x0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:175 +0x46
github.com/roboll/helmfile/pkg/app.(*App).ForEachState.func1(0xc0000d0d80, 0xc0000d0d80, 0x0, 0x0, 0xc0006db200)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:583 +0xbb
github.com/roboll/helmfile/pkg/app.(*App).visitStates.func1(0x213cf27, 0xd, 0xc00003e150, 0x26, 0x0, 0x0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:523 +0x7ec
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles.func1(0x0, 0x3471560)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:359 +0x9d
github.com/roboll/helmfile/pkg/app.(*App).within(0xc0002cca20, 0x2131895, 0x1, 0xc0006be500, 0xc0006be4c0, 0x2)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:301 +0x602
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles(0xc0002cca20, 0x0, 0x0, 0x30a68d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:353 +0x2f2
github.com/roboll/helmfile/pkg/app.(*App).visitStates(0xc0002cca20, 0x0, 0x0, 0x30a68d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:435 +0x10b
github.com/roboll/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport(0xc0002cca20, 0x0, 0x0, 0xc0006be7e8, 0x0, 0x0, 0x0, 0x10, 0xc0004bf5e0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:699 +0x45c
github.com/roboll/helmfile/pkg/app.(*App).ForEachState(0xc0002cca20, 0xc0006be850, 0x0, 0x0, 0x0, 0x2112c60, 0xc0004bf5e0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:579 +0xb2
github.com/roboll/helmfile/pkg/app.(*App).Template(0xc0002cca20, 0x26a62a0, 0xc0004bf5e0, 0xc0004bf5e0, 0xc000359298)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:174 +0x79
main.main.func5(0xc0002cca20, 0xc00018cc60, 0x0, 0xc0004bf5d0, 0x0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/main.go:253 +0x6d
main.action.func1(0xc00018cc60, 0x0, 0xc00018cc60)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/main.go:681 +0xd4
github.com/urfave/cli.HandleAction(0x1ec5400, 0xc0004bf0b0, 0xc00018cc60, 0xc00007e700, 0x0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/.brew_home/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0x213806b, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2174b24, 0x3d, 0x0, ...)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/.brew_home/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x9e8
github.com/urfave/cli.(*App).Run(0xc0000b0000, 0xc0000ac180, 0x3, 0x3, 0x0, 0x0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/.brew_home/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x741
main.main()
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/main.go:487 +0x3484
```

to reproduce the issue, this is my helmfile file:

```
---
repositories:
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"

releases:
- name:  "prometheus"
  chart: "stable/prometheus-operator"
  namespace: "monitoring"
  hooks:
  - events: ["prepare"]
    command: /usr/local/bin/kubectl apply -f namespace.yaml
```

some notes about my environment:

- I am running OSX Catalina 10.15.4
- helmfile version v0.117.0

alternatively, if I don't set the full path of the kubectl binary I get a different panic message:

```
panic: unexpected error: exec: "kubectl apply -f namespace.yaml": executable file not found in $PATH

goroutine 1 [running]:
github.com/roboll/helmfile/pkg/helmexec.combinedOutput(0xc0000c51e0, 0x0, 0x25, 0xc000111a10, 0xc000700800, 0x25, 0x40)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/helmexec/runner.go:70 +0x59f
github.com/roboll/helmfile/pkg/helmexec.ShellRunner.Execute(0x2131895, 0x1, 0x0, 0xc0004cce60, 0x1f, 0x30a68d0, 0x0, 0x0, 0xc000111a10, 0xc000111a10, ...)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/helmexec/runner.go:36 +0xd9
github.com/roboll/helmfile/pkg/event.(*Bus).Trigger(0xc00081d008, 0x2136ac0, 0x7, 0x0, 0x0, 0xc00081cfd8, 0x0, 0xc0004ccae0, 0x1a)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/event/bus.go:96 +0x906
github.com/roboll/helmfile/pkg/state.(*HelmState).triggerReleaseEvent(0xc0005c8000, 0x2136ac0, 0x7, 0x0, 0x0, 0xc00009f080, 0x213806b, 0x8, 0x0, 0x0, ...)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/state/state.go:1452 +0x2d0
github.com/roboll/helmfile/pkg/state.(*HelmState).triggerPrepareEvent(...)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/state/state.go:1423
github.com/roboll/helmfile/pkg/state.(*HelmState).PrepareReleases(0xc0005c8000, 0x26b3300, 0xc0001b8000, 0x213806b, 0x8, 0x0, 0x0, 0x203000)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/state/state.go:1403 +0x165
github.com/roboll/helmfile/pkg/app.(*App).template(0xc00032c480, 0xc00056e180, 0x26a62a0, 0xc00049e350, 0x30, 0x2038220, 0xc00032c501, 0xc00056e180)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:1159 +0x17a
github.com/roboll/helmfile/pkg/app.(*App).Template.func1(0xc00056e180, 0xc00056e180, 0x26b3300, 0xc0001b8000, 0x0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:175 +0x46
github.com/roboll/helmfile/pkg/app.(*App).ForEachState.func1(0xc0005c8000, 0xc0005c8000, 0x0, 0x0, 0xc0005506c0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:583 +0xbb
github.com/roboll/helmfile/pkg/app.(*App).visitStates.func1(0x213cf27, 0xd, 0xc00003e150, 0x26, 0x0, 0x0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:523 +0x7ec
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles.func1(0x0, 0x3470108)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:359 +0x9d
github.com/roboll/helmfile/pkg/app.(*App).within(0xc00032c480, 0x2131895, 0x1, 0xc00081e500, 0xc00081e4c0, 0x2)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:301 +0x602
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles(0xc00032c480, 0x0, 0x0, 0x30a68d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:353 +0x2f2
github.com/roboll/helmfile/pkg/app.(*App).visitStates(0xc00032c480, 0x0, 0x0, 0x30a68d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:435 +0x10b
github.com/roboll/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport(0xc00032c480, 0x0, 0x0, 0xc00081e7e8, 0x0, 0x0, 0x0, 0x10, 0xc00049e350)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:699 +0x45c
github.com/roboll/helmfile/pkg/app.(*App).ForEachState(0xc00032c480, 0xc00081e850, 0x0, 0x0, 0x0, 0x2112c60, 0xc00049e350)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:579 +0xb2
github.com/roboll/helmfile/pkg/app.(*App).Template(0xc00032c480, 0x26a62a0, 0xc00049e350, 0xc00049e350, 0xc000716010)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/pkg/app/app.go:174 +0x79
main.main.func5(0xc00032c480, 0xc0001e82c0, 0x0, 0xc00049e340, 0x0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/main.go:253 +0x6d
main.action.func1(0xc0001e82c0, 0x0, 0xc0001e82c0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/main.go:681 +0xd4
github.com/urfave/cli.HandleAction(0x1ec5400, 0xc00049f050, 0xc0001e82c0, 0xc0003da000, 0x0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/.brew_home/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0x213806b, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2174b24, 0x3d, 0x0, ...)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/.brew_home/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x9e8
github.com/urfave/cli.(*App).Run(0xc000186000, 0xc000182180, 0x3, 0x3, 0x0, 0x0)
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/.brew_home/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x741
main.main()
	/private/tmp/helmfile-20200524-53128-oiyr6u/helmfile-0.117.0/main.go:487 +0x3484
```

and yes kubectl it's on my path:

```
$ which kubectl
/usr/local/bin/kubectl
```

**Comment by korporationcl** [comment]
well after trying a bit harder I found that command parameter expects only the name of the command https://gitmemory.com/issue/roboll/helmfile/552/489775881. I wish the documentation would be a bit more clear about that.
