### ISSUE TITLE
template fails cause crash

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#233]
This happens when using requiredEnv inside of a values file and the env variable is not set.

```
2018/08/26 08:33:34 [bug] this code path shouldn't be arrived: helmfile is expected to exit from within the `cleanup` func in main.go: template: stringTemplate:41:41: executing "stringTemplate" at <requiredEnv "HELM_AC...>: error calling requiredEnv: required env var `HELM_ACCOUNT_ID` is not set
panic: [bug] this code path shouldn't be arrived: helmfile is expected to exit from within the `cleanup` func in main.go: template: stringTemplate:41:41: executing "stringTemplate" at <requiredEnv "HELM_AC...>: error calling requiredEnv: required env var `HELM_ACCOUNT_ID` is not set

goroutine 1 [running]:
log.Panicf(0x144bde3, 0x75, 0xc42015b728, 0x1, 0x1)
	/usr/local/Cellar/go/1.10.3/libexec/src/log/log.go:333 +0xda
main.main()
	/Users/sstarcher/go/src/github.com/roboll/helmfile/main.go:388 +0x17d8
```

**Comment by sstarcher** [comment]
using latest master as of today
