### ISSUE TITLE
SIGSEGV 0.33.4

### ISSUE THREAD

**Issue by sruon** [roboll/helmfile#320]
`helmfile -e stage sync`

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x766e6b]

goroutine 1 [running]:
github.com/roboll/helmfile/vendor/github.com/urfave/cli.HandleAction.func1(0xc420154f48)
	/go/src/github.com/roboll/helmfile/vendor/github.com/urfave/cli/app.go:474 +0x279
panic(0x7d10a0, 0xa79ae0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
main.(*app).FindAndIterateOverDesiredStates(0xc420154a80, 0x0, 0x0, 0xc420154af0, 0x0, 0x0, 0xaa6948, 0x0, 0x0, 0x7fffd6ed9098, ...)
	/go/src/github.com/roboll/helmfile/main.go:630 +0x4db
main.findAndIterateOverDesiredStatesUsingFlags(0xc4200d4c80, 0xc420154af0, 0xc420154b10, 0x16)
	/go/src/github.com/roboll/helmfile/main.go:568 +0x2f3
main.main.func6(0xc4200d4c80, 0x0, 0x0)
	/go/src/github.com/roboll/helmfile/main.go:273 +0x46
reflect.Value.call(0x7b7380, 0x859aa0, 0x13, 0x83a5cf, 0x4, 0xc420154ee8, 0x1, 0x1, 0xc42000e140, 0x82de60, ...)
	/usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x7b7380, 0x859aa0, 0x13, 0xc420154ee8, 0x1, 0x1, 0x4, 0xc420095350, 0x5)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/roboll/helmfile/vendor/github.com/urfave/cli.HandleAction(0x7b7380, 0x859aa0, 0xc4200d4c80, 0x0, 0x0)
	/go/src/github.com/roboll/helmfile/vendor/github.com/urfave/cli/app.go:483 +0x173
github.com/roboll/helmfile/vendor/github.com/urfave/cli.Command.Run(0x83ab63, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x85390a, 0x43, 0x0, ...)
	/go/src/github.com/roboll/helmfile/vendor/github.com/urfave/cli/command.go:186 +0x999
github.com/roboll/helmfile/vendor/github.com/urfave/cli.(*App).Run(0xc420001200, 0xc42000e0c0, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/roboll/helmfile/vendor/github.com/urfave/cli/app.go:237 +0x546
main.main()
	/go/src/github.com/roboll/helmfile/main.go:474 +0x1f79
```

**Comment by sruon** [comment]
Looks related to #318 fix

**Comment by mumoshu** [comment]
@sruon Thanks for the report! #321 should fix this. Could you try v0.33.5?

**Comment by sruon** [comment]
@mumoshu looks fixed, thanks !

**Comment by mumoshu** [comment]
Glad it worked! Thx again for your support.
