### ISSUE TITLE
README typo causes app crash

### ISSUE THREAD

**Issue by robvadai** [roboll/helmfile#373]
The app crashes if Go templates are not well-defined.

Steps to reproduce:

1. Copy this line: https://github.com/roboll/helmfile/blame/master/README.md#L405
2. Run any `helmfile` command (I did `lint` and `sync`)
3. See a beautiful crash stacktrace:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x136ac2e]

goroutine 1 [running]:
github.com/roboll/helmfile/vendor/github.com/urfave/cli.HandleAction.func1(0xc42014ef08)
	/go/src/github.com/roboll/helmfile/vendor/github.com/urfave/cli/app.go:474 +0x279
panic(0x13d7220, 0x1683ab0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
bytes.(*Buffer).Bytes(...)
	/usr/local/go/src/bytes/buffer.go:55
main.(*twoPassRenderer).renderEnvironment(0xc42014e8c0, 0xc4200c2900, 0x219, 0x419, 0x104f210, 0xc42014e640, 0x10988bb)
	/go/src/github.com/roboll/helmfile/main.go:657 +0x1ce
main.(*twoPassRenderer).renderTemplate(0xc42014e8c0, 0xc4200c2900, 0x219, 0x419, 0x419, 0x0, 0x0)
	/go/src/github.com/roboll/helmfile/main.go:673 +0x6a
main.(*app).FindAndIterateOverDesiredStates(0xc42014ea10, 0x7ffeefbfed60, 0x5b, 0xc420101220, 0x0, 0x0, 0x16b0280, 0x0, 0x0, 0x7ffeefbfed57, ...)
	/go/src/github.com/roboll/helmfile/main.go:711 +0x2cd
main.findAndIterateOverDesiredStatesUsingFlagsWithReverse(0xc4200d2c80, 0x0, 0xc4200714d0, 0x1, 0xc4200714d0)
	/go/src/github.com/roboll/helmfile/main.go:604 +0x387
main.findAndIterateOverDesiredStatesUsingFlags(0xc4200d2c80, 0xc4200714d0, 0x20, 0xc420099a10)
	/go/src/github.com/roboll/helmfile/main.go:568 +0x3a
main.main.func5(0xc4200d2c80, 0x0, 0x0)
	/go/src/github.com/roboll/helmfile/main.go:240 +0x65
reflect.Value.call(0x13bd020, 0x1460bc0, 0x13, 0x144163d, 0x4, 0xc42014eea8, 0x1, 0x1, 0xc420030080, 0x1434ec0, ...)
	/usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x13bd020, 0x1460bc0, 0x13, 0xc42014eea8, 0x1, 0x1, 0x4, 0xc4200a1350, 0x5)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/roboll/helmfile/vendor/github.com/urfave/cli.HandleAction(0x13bd020, 0x1460bc0, 0xc4200d2c80, 0x0, 0x0)
	/go/src/github.com/roboll/helmfile/vendor/github.com/urfave/cli/app.go:483 +0x173
github.com/roboll/helmfile/vendor/github.com/urfave/cli.Command.Run(0x1441a25, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x145440d, 0x27, 0x0, ...)
	/go/src/github.com/roboll/helmfile/vendor/github.com/urfave/cli/command.go:186 +0x999
github.com/roboll/helmfile/vendor/github.com/urfave/cli.(*App).Run(0xc420001200, 0xc42001c0c0, 0x6, 0x6, 0x0, 0x0)
	/go/src/github.com/roboll/helmfile/vendor/github.com/urfave/cli/app.go:237 +0x546
main.main()
	/go/src/github.com/roboll/helmfile/main.go:503 +0x1ffc
```

Firstly, the README should be updated because an `if` statement needs no parentheses in Go templates: https://gist.github.com/techslides/8957209

Secondly, exceptions should be gracefully handled with a nice error message instead of crashing the app.

Used with helmfile version 0.37

**Comment by davidovich** [comment]
Thank you for the report, fixing now
