### ISSUE TITLE
0.75.0: --state-values-set panic: value of type interface {} is not assignable to type string

### ISSUE THREAD

**Issue by bitsofinfo** [roboll/helmfile#677]
I have an environments file that contains something like this

```
environments:
  dog:
    values:
      - chart-values.yaml
```

chart-values.yaml contains
```
appdeploy:
  chartValues:
    values:
      replicaCount: 1
```

This work fine when running helmfile normally, however, once I try to tweak that state/env value with 

```
--state-values-set appdeploy.chartValues.values.replicaCount=3
```

I get this:

```
first-pass rendering starting for "deployments.helmfile.yaml.part.0": inherited=<nil>, overrode=&{dog map[appdeploy:map[chartValues:map[values:map[replicaCount:3]]]] map[]}
first-pass uses: &{dog map[appdeploy:map[chartValues:map[values:map[replicaCount:3]]]] map[]}
error in first-pass rendering: result of "deployments.helmfile.yaml.part.0":
 0: bases:
 1:   - environments.yaml

first-pass produced: &{dog map[appdeploy:map[chartValues:map[values:map[replicaCount:3]]]] map[]}
first-pass rendering result of "deployments.helmfile.yaml.part.0": {dog map[appdeploy:map[chartValues:map[values:map[replicaCount:3]]]] map[]}
second-pass rendering result of "deployments.helmfile.yaml.part.0":
 0: bases:
 1:   - environments.yaml

first-pass rendering starting for "environments.yaml.part.0": inherited=&{dog map[appdeploy:map[chartValues:map[values:map[replicaCount:3]]]] map[]}, overrode=<nil>
first-pass uses: &{dog map[appdeploy:map[chartValues:map[values:map[replicaCount:3]]]] map[]}
panic: reflect.Value.MapIndex: value of type interface {} is not assignable to type string [recovered]
        panic: reflect.Value.MapIndex: value of type interface {} is not assignable to type string

goroutine 1 [running]:
github.com/urfave/cli.HandleAction.func1(0xc00052ef08)
        /go/pkg/mod/github.com/urfave/cli@v0.0.0-20160620154522-6011f165dc28/app.go:474 +0x287
panic(0x1850fc0, 0xc0000b7480)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
reflect.Value.assignTo(0x1896320, 0xc0000b7440, 0x94, 0x19cafb0, 0x16, 0x1850fc0, 0x0, 0x1896320, 0xc0000b7440, 0x94)
        /usr/local/go/src/reflect/value.go:2339 +0x437
reflect.Value.MapIndex(0x189a700, 0xc00034f500, 0x15, 0x1896320, 0xc0000b7440, 0x94, 0x1896320, 0xc0000b7470, 0x94)
        /usr/local/go/src/reflect/value.go:1104 +0x8c
github.com/imdario/mergo.deepMerge(0x189a700, 0xc00034f500, 0x15, 0x1898180, 0xc00030df80, 0x15, 0xc00052ceb0, 0x2, 0xc0000b8740, 0x0, ...)
        /go/pkg/mod/github.com/imdario/mergo@v0.3.6/merge.go:90 +0x46f
github.com/imdario/mergo.deepMerge(0x189a700, 0xc0000b8710, 0x195, 0x189a700, 0xc0000b86f0, 0x195, 0xc00052ceb0, 0x1, 0xc0000b8740, 0x0, ...)
        /go/pkg/mod/github.com/imdario/mergo@v0.3.6/merge.go:115 +0x97d
github.com/imdario/mergo.deepMerge(0x1934700, 0xc0000b8700, 0x199, 0x1934700, 0xc0000b86e0, 0x199, 0xc00052ceb0, 0x0, 0xc0000b8740, 0x199, ...)
        /go/pkg/mod/github.com/imdario/mergo@v0.3.6/merge.go:72 +0x24ab
github.com/imdario/mergo.merge(0x18be0a0, 0xc0000b8700, 0x18be0a0, 0xc0000b86e0, 0xc00052d120, 0x1, 0x1, 0x0, 0x1b4)
        /go/pkg/mod/github.com/imdario/mergo@v0.3.6/merge.go:251 +0x299
github.com/imdario/mergo.Merge(...)
        /go/pkg/mod/github.com/imdario/mergo@v0.3.6/merge.go:206
github.com/roboll/helmfile/pkg/state.(*HelmState).loadEnvValues(0xc00025ef00, 0x7ffeefbff971, 0x8, 0xc0004b06c0, 0x19f2808, 0x19f2c68, 0xc00034f9b0, 0x1, 0xc0001d1b00)
        /home/circleci/workspace/helmfile/pkg/state/create.go:239 +0x2a1
github.com/roboll/helmfile/pkg/state.(*StateCreator).LoadEnvValues(0xc0000c3dc0, 0xc00025e960, 0x7ffeefbff971, 0x8, 0xc0004b06c0, 0xc00025e960, 0x0, 0x0)
        /home/circleci/workspace/helmfile/pkg/state/create.go:113 +0xc2
github.com/roboll/helmfile/pkg/state.(*StateCreator).ParseAndLoad(0xc0000c3dc0, 0xc0004d4800, 0x382, 0x400, 0x19bab54, 0x1, 0xc000034180, 0x18, 0x7ffeefbff971, 0x8, ...)
        /home/circleci/workspace/helmfile/pkg/state/create.go:146 +0x138
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).renderPrestate(0xc0001cc5a0, 0xc0004b06c0, 0x19bab54, 0x1, 0xc000034180, 0x18, 0xc0004b6000, 0x382, 0x582, 0x0, ...)
        /home/circleci/workspace/helmfile/pkg/app/two_pass_renderer.go:52 +0x454
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).twoPassRenderTemplateToYaml(0xc0001cc5a0, 0xc0000b9e00, 0x0, 0x19bab54, 0x1, 0xc000034180, 0x18, 0xc0004b6000, 0x382, 0x582, ...)
        /home/circleci/workspace/helmfile/pkg/app/two_pass_renderer.go:96 +0xfb
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).renderTemplatesToYamlWithEnv(...)
        /home/circleci/workspace/helmfile/pkg/app/two_pass_renderer.go:78
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).renderAndLoad(0xc0001cc5a0, 0xc0000b9e00, 0x0, 0x19bab54, 0x1, 0xc0000c1d60, 0x11, 0xc0004b6000, 0x382, 0x582, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:170 +0x283
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).loadFileWithOverrides(0xc0001cc5a0, 0xc0000b9e00, 0x0, 0x19bab54, 0x1, 0xc0000c1d00, 0x11, 0x0, 0xc0000c3b80, 0x1, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:105 +0x1f4
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).loadFile(...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:84
github.com/roboll/helmfile/pkg/state.(*StateCreator).loadBases(0xc0000c3bc0, 0xc0000b9e00, 0xc00025e3c0, 0x19bab54, 0x1, 0x1, 0xc0003da2e0, 0x19)
        /home/circleci/workspace/helmfile/pkg/state/create.go:159 +0xe2
github.com/roboll/helmfile/pkg/state.(*StateCreator).ParseAndLoad(0xc0000c3bc0, 0xc000458040, 0x1c, 0x40, 0x19bab54, 0x1, 0xc0003da2e0, 0x19, 0x7ffeefbff971, 0x8, ...)
        /home/circleci/workspace/helmfile/pkg/state/create.go:141 +0xe6
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).load(0xc0001cc5a0, 0xc000458040, 0x1c, 0x40, 0x19bab54, 0x1, 0xc0003da2e0, 0x19, 0x1, 0x0, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:139 +0x11a
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).renderAndLoad(0xc0001cc5a0, 0x0, 0xc0003d0f80, 0x19bab54, 0x1, 0xc0003da2e0, 0x19, 0xc000420000, 0xdf4, 0xff4, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:176 +0x345
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).loadFileWithOverrides(0xc0001cc5a0, 0x0, 0xc0003d0f80, 0x19bab54, 0x1, 0x7ffeefbff930, 0x19, 0x1, 0x0, 0x203000, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:105 +0x1f4
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).Load(0xc0001cc5a0, 0x7ffeefbff930, 0x19, 0xc0003c67a0, 0x1, 0x1, 0xc0003c6800, 0x1, 0x1, 0x7ffeefbff930, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:53 +0x473
github.com/roboll/helmfile/pkg/app.(*App).loadDesiredStateFromYaml(0xc0003f8000, 0x7ffeefbff930, 0x19, 0xc000256510, 0x1, 0x1, 0x0, 0x0, 0xc0003c67a0)
        /home/circleci/workspace/helmfile/pkg/app/app.go:244 +0x1d2
github.com/roboll/helmfile/pkg/app.(*App).visitStates.func1(0x7ffeefbff930, 0x19, 0xc000400060, 0x4f, 0x0, 0x0)
        /home/circleci/workspace/helmfile/pkg/app/app.go:257 +0x1be
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles.func1(0x0, 0x0)
        /home/circleci/workspace/helmfile/pkg/app/app.go:215 +0x9d
github.com/roboll/helmfile/pkg/app.(*App).within(0xc0003f8000, 0x19bab54, 0x1, 0xc0003c4f80, 0xc000256888, 0x2)
        /home/circleci/workspace/helmfile/pkg/app/app.go:157 +0x725
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles(0xc0003f8000, 0x7ffeefbff930, 0x19, 0xc0001cc2a0, 0x20, 0x190a660)
        /home/circleci/workspace/helmfile/pkg/app/app.go:209 +0x29f
github.com/roboll/helmfile/pkg/app.(*App).visitStates(0xc0003f8000, 0x7ffeefbff930, 0x19, 0xc0003c6370, 0x1, 0x1, 0xc0003c6540, 0x1, 0x1, 0x0, ...)
        /home/circleci/workspace/helmfile/pkg/app/app.go:250 +0xd4
github.com/roboll/helmfile/pkg/app.(*App).VisitDesiredStatesWithReleasesFiltered(0xc0003f8000, 0x7ffeefbff930, 0x19, 0xc0003c6530, 0xc000256a01, 0xc0003d0d40)
        /home/circleci/workspace/helmfile/pkg/app/app.go:398 +0x426
github.com/roboll/helmfile/pkg/app.(*App).ForEachState(0xc0003f8000, 0xc0003d0d40, 0xc0003c6520, 0x199e8a0)
        /home/circleci/workspace/helmfile/pkg/app/app.go:344 +0x81
github.com/roboll/helmfile/pkg/app.(*App).Apply(0xc0003f8000, 0x1b6aec0, 0xc0003c6520, 0xc0003c6520, 0x18e4b00)
        /home/circleci/workspace/helmfile/pkg/app/app.go:126 +0x6e
main.main.func8(0xc0003f8000, 0xc0003ec140, 0xc0003ce270, 0xc0003c6500, 0x0)
        /home/circleci/workspace/helmfile/main.go:299 +0x6d
main.action.func1(0xc0003ec140, 0x0, 0x0)
        /home/circleci/workspace/helmfile/main.go:530 +0x121
reflect.Value.call(0x1869420, 0xc0003c6070, 0x13, 0x19bb542, 0x4, 0xc000256ea8, 0x1, 0x1, 0xc0003c4cc0, 0x1011ac3, ...)
        /usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x1869420, 0xc0003c6070, 0x13, 0xc000256ea8, 0x1, 0x1, 0xc0003e6340, 0xc0003e6398, 0x140)
        /usr/local/go/src/reflect/value.go:308 +0xa4
github.com/urfave/cli.HandleAction(0x1869420, 0xc0003c6070, 0xc0003ec140, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v0.0.0-20160620154522-6011f165dc28/app.go:483 +0x1ff
github.com/urfave/cli.Command.Run(0x19bc21a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19e591c, 0x3f, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v0.0.0-20160620154522-6011f165dc28/command.go:186 +0x8d1
github.com/urfave/cli.(*App).Run(0xc0003be000, 0xc0000b4000, 0xe, 0xe, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v0.0.0-20160620154522-6011f165dc28/app.go:237 +0x601
main.main()
        /home/circleci/workspace/helmfile/main.go:383 +0x2644
```

**Comment by bitsofinfo** [comment]
i think i might still be confused, i might be needing to set --set-state-value=...?

**Comment by XBeg9** [comment]
@mumoshu I am facing the same issue on latest 0.79

```bash
panic: reflect.Value.MapIndex: value of type interface {} is not assignable to type string [recovered]
        panic: reflect.Value.MapIndex: value of type interface {} is not assignable to type string

goroutine 1 [running]:
github.com/urfave/cli.HandleAction.func1(0xc00026ce78)
        /private/tmp/helmfile-20190619-46501-1wenva6/helmfile-0.79.0/pkg/mod/github.com/urfave/cli@v0.0.0-20160620154522-6011f165dc28/app.go:474 +0x287
panic(0x18436c0, 0xc0004e47c0)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5
reflect.Value.assignTo(0x18877e0, 0xc0004e47a0, 0x94, 0x19b7db3, 0x16, 0x18436c0, 0x0, 0x18877e0, 0xc0004e47a0, 0x94)```

**Comment by mumoshu** [comment]
@XBeg9 Thanks for reporting! Would you mind sharing your files for reproduction? I'm pretty blind and unable to reproduce it without examples...

**Comment by XBeg9** [comment]
@mumoshu hm, maybe the problem is inside the `helm secrets` plugin? I can't share my secrets with you :), but I will try to find how to repro the issue.

To others, please do to fix the issue, this will downgrade your helmfile to 0.73.2:
```ssh
brew uninstall helmfile
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/d4285208c9aadd0f17f5e306de64463a7755c338/Formula/helmfile.rb
```

**Comment by mumoshu** [comment]
@XBeg9 Thanks! Are you using environment secrets?
